# Generated by Django 2.0.7 on 2018-07-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=32, unique=True)),
                ('ctime', models.DateField(auto_now_add=True, null=True)),
                ('uptime', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
