# Generated by Django 2.0.7 on 2018-07-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_userinfo_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_group',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
