# Generated by Django 2.0.7 on 2018-07-16 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20180716_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='test',
            field=models.EmailField(error_messages={'invalid': '请输入密码'}, max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.UserGroup'),
        ),
    ]
